### ISSUE TITLE
React Dashboard Error

### ISSUE THREAD

**Issue by ggates1020** [cdta-digital-services/.github#40]
**Jira:** `CDTA-2249`  
**Reporter:** Jennifer Southern  
**Assignee (Jira):** Jennifer Southern  
**Created:** 11/12/2021 12:07 PM  
**Story Points:** 5.0  

---

[https://dev.cdta.org/react/dashboard/|https://dev.cdta.org/react/dashboard/]

No one has looked at this since our developer Don left. It appears to load for a moment and then the screen goes blank and there is an error in the console:

”l.map is not a function”

This can be worked on directly on the dev server (52.224.109.176) as there isn’t another environment set up for it at this time. 

(From comment below)
I was taking a peek in the crontab and I think you'll find some of the JSON data you are looking for is generated in this area:

/var/www/scripts/tracker

I noticed some notes in the crontab about the dashboard for that directory.
